//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebcreteAPI
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.concretego.com/", ConfigurationName="WebcreteAPI.WebcreteAPISoap")]
    public interface WebcreteAPISoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/GetPublicKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebcreteAPI.GetPublicKeyResponse> GetPublicKeyAsync(WebcreteAPI.GetPublicKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebcreteAPI.LoginResponse> LoginAsync(WebcreteAPI.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/Login2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebcreteAPI.Login2Response> Login2Async(WebcreteAPI.Login2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/ProcessRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebcreteAPI.ProcessRequestResponse> ProcessRequestAsync(WebcreteAPI.ProcessRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebcreteAPI.LogoutResponse> LogoutAsync(WebcreteAPI.LogoutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.concretego.com/")]
    public partial class TicketHeader
    {
        
        private System.Guid ticketField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ticket
        {
            get
            {
                return this.ticketField;
            }
            set
            {
                this.ticketField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPublicKey", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class GetPublicKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string appID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=1)]
        public string apiKey;
        
        public GetPublicKeyRequest()
        {
        }
        
        public GetPublicKeyRequest(string appID, string apiKey)
        {
            this.appID = appID;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPublicKeyResponse", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class GetPublicKeyResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPI.TicketHeader TicketHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string GetPublicKeyResult;
        
        public GetPublicKeyResponse()
        {
        }
        
        public GetPublicKeyResponse(WebcreteAPI.TicketHeader TicketHeader, string GetPublicKeyResult)
        {
            this.TicketHeader = TicketHeader;
            this.GetPublicKeyResult = GetPublicKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class LoginRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPI.TicketHeader TicketHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=2)]
        public string slug;
        
        public LoginRequest()
        {
        }
        
        public LoginRequest(WebcreteAPI.TicketHeader TicketHeader, string userName, byte[] password, string slug)
        {
            this.TicketHeader = TicketHeader;
            this.userName = userName;
            this.password = password;
            this.slug = slug;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class LoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public bool LoginResult;
        
        public LoginResponse()
        {
        }
        
        public LoginResponse(bool LoginResult)
        {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login2", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class Login2Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPI.TicketHeader TicketHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=2)]
        public string slug;
        
        public Login2Request()
        {
        }
        
        public Login2Request(WebcreteAPI.TicketHeader TicketHeader, string userName, string password, string slug)
        {
            this.TicketHeader = TicketHeader;
            this.userName = userName;
            this.password = password;
            this.slug = slug;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login2Response", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class Login2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public bool Login2Result;
        
        public Login2Response()
        {
        }
        
        public Login2Response(bool Login2Result)
        {
            this.Login2Result = Login2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessRequest", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class ProcessRequestRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPI.TicketHeader TicketHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string request;
        
        public ProcessRequestRequest()
        {
        }
        
        public ProcessRequestRequest(WebcreteAPI.TicketHeader TicketHeader, string request)
        {
            this.TicketHeader = TicketHeader;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessRequestResponse", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class ProcessRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string ProcessRequestResult;
        
        public ProcessRequestResponse()
        {
        }
        
        public ProcessRequestResponse(string ProcessRequestResult)
        {
            this.ProcessRequestResult = ProcessRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logout", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class LogoutRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPI.TicketHeader TicketHeader;
        
        public LogoutRequest()
        {
        }
        
        public LogoutRequest(WebcreteAPI.TicketHeader TicketHeader)
        {
            this.TicketHeader = TicketHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class LogoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public bool LogoutResult;
        
        public LogoutResponse()
        {
        }
        
        public LogoutResponse(bool LogoutResult)
        {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WebcreteAPISoapChannel : WebcreteAPI.WebcreteAPISoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WebcreteAPISoapClient : System.ServiceModel.ClientBase<WebcreteAPI.WebcreteAPISoap>, WebcreteAPI.WebcreteAPISoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebcreteAPISoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebcreteAPISoapClient.GetBindingForEndpoint(endpointConfiguration), WebcreteAPISoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebcreteAPISoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebcreteAPISoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebcreteAPISoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebcreteAPISoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebcreteAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPI.GetPublicKeyResponse> WebcreteAPI.WebcreteAPISoap.GetPublicKeyAsync(WebcreteAPI.GetPublicKeyRequest request)
        {
            return base.Channel.GetPublicKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPI.GetPublicKeyResponse> GetPublicKeyAsync(string appID, string apiKey)
        {
            WebcreteAPI.GetPublicKeyRequest inValue = new WebcreteAPI.GetPublicKeyRequest();
            inValue.appID = appID;
            inValue.apiKey = apiKey;
            return ((WebcreteAPI.WebcreteAPISoap)(this)).GetPublicKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPI.LoginResponse> WebcreteAPI.WebcreteAPISoap.LoginAsync(WebcreteAPI.LoginRequest request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPI.LoginResponse> LoginAsync(WebcreteAPI.TicketHeader TicketHeader, string userName, byte[] password, string slug)
        {
            WebcreteAPI.LoginRequest inValue = new WebcreteAPI.LoginRequest();
            inValue.TicketHeader = TicketHeader;
            inValue.userName = userName;
            inValue.password = password;
            inValue.slug = slug;
            return ((WebcreteAPI.WebcreteAPISoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPI.Login2Response> WebcreteAPI.WebcreteAPISoap.Login2Async(WebcreteAPI.Login2Request request)
        {
            return base.Channel.Login2Async(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPI.Login2Response> Login2Async(WebcreteAPI.TicketHeader TicketHeader, string userName, string password, string slug)
        {
            WebcreteAPI.Login2Request inValue = new WebcreteAPI.Login2Request();
            inValue.TicketHeader = TicketHeader;
            inValue.userName = userName;
            inValue.password = password;
            inValue.slug = slug;
            return ((WebcreteAPI.WebcreteAPISoap)(this)).Login2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPI.ProcessRequestResponse> WebcreteAPI.WebcreteAPISoap.ProcessRequestAsync(WebcreteAPI.ProcessRequestRequest request)
        {
            return base.Channel.ProcessRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPI.ProcessRequestResponse> ProcessRequestAsync(WebcreteAPI.TicketHeader TicketHeader, string request)
        {
            WebcreteAPI.ProcessRequestRequest inValue = new WebcreteAPI.ProcessRequestRequest();
            inValue.TicketHeader = TicketHeader;
            inValue.request = request;
            return ((WebcreteAPI.WebcreteAPISoap)(this)).ProcessRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPI.LogoutResponse> WebcreteAPI.WebcreteAPISoap.LogoutAsync(WebcreteAPI.LogoutRequest request)
        {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPI.LogoutResponse> LogoutAsync(WebcreteAPI.TicketHeader TicketHeader)
        {
            WebcreteAPI.LogoutRequest inValue = new WebcreteAPI.LogoutRequest();
            inValue.TicketHeader = TicketHeader;
            return ((WebcreteAPI.WebcreteAPISoap)(this)).LogoutAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebcreteAPISoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebcreteAPISoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebcreteAPISoap))
            {
                return new System.ServiceModel.EndpointAddress("http://api1.concretego.com/webcreteapi.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebcreteAPISoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://api1.concretego.com/webcreteapi.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebcreteAPISoap,
            
            WebcreteAPISoap12,
        }
    }
}
